Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  # If I mount anywhere other than /vagrant, it uses NFS instead of rsync :(
  config.vm.synced_folder "proj", "/vagrant", type: "rsync"
end
